name: shoko_api_core
description: Package for fast create api with dart_frog
version: 1.0.3
repository: https://github.com/ShokoTeam/shoko_api_core

environment:
  sdk: ">=3.9.2"

dependencies:
  dart_frog: ^1.2.4

dev_dependencies:
  lints: ^5.0.0
  flutter_lints: ^5.0.0
  # test: ^1.24.0
