name: exmaple_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shoko_api_core:
    path: ../shoko_api_core

dev_dependencies:
  build_runner: ^2.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.3
  test: ^1.25.5
