name: shoko_api_core_supabase
description: Extension for shoko_api_core to work with Supabase
version: 1.0.1
repository: https://github.com/ShokoTeam/shoko_api_core

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  shoko_api_core: ^1.0.0
  supabase: ^2.6.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
